# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11I1b-j1ifwQ7KNGxiEqMhxyXG6aWdUQY
"""

import os
import gradio as gr
from transformers import pipeline

#Load the Hugging Face pipeline
generator = pipeline("text-generation", model="gpt2")
classifier = pipeline("sentiment-analysis", model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

def analyze_and_generate(user_text):
    sentiment_result = classifier(user_text)[0]
    sentiment_label = sentiment_result['label']
    sentiment_score = sentiment_result['score']

    generated_outputs = generator(user_text, max_new_tokens=50, num_return_sequences=1)
    generated_text = generated_outputs[0]['generated_text']

    sentiment_summary = f"Analysis: {sentiment_label} (confidence: {sentiment_score * 100}%)"

    return sentiment_summary, generated_text

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# AI Text Assitant")
    gr.Markdown("Enter a prompt below to analyze its sentiment and let AI complete your text.")

    with gr.Row():
        input_text = gr.Textbox(
            label="Your input text",
            placeholder="The workshop was just amazing I learned alot It helped me to learn about hugging face",
            lines=3,
        )
        submit_button = gr.Button("submit", variant="primary")

    with gr.Row():
        sentiment_output = gr.Textbox(label="Detected Sentiment Analysis")
        generated_output = gr.Textbox(label="AI Text Continuation", lines=5)

    submit_button.click(
    fn=analyze_and_generate,
    inputs=input_text,
    outputs=[sentiment_output, generated_output]
    )

    gr.Examples(
    examples=[["The workshop was just amazing"],["I learned alot"],["It helped me to learn about hugging face"]],
    inputs=input_text
    )

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    demo.launch(server_name="0.0.0.0.",
                server_port=port,
                debug=True
               )
