# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FA1gGAD02LDQdP7FhgKq9an2ZKWPfY96
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# gradio>=4.0.0
# transformers
# torch